name: 'Build Pull Request'

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: taskany-inc/release/.github/workflows/checkout.yml@main
        
      - name: Setup packages
        run: npm ci
        
      - name: Lint
        run: npm run lint
      
      - name: Unit
        run: npm run test
        
      - name: Build
        run: npm run build
