name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  checkout:
    uses: taskany-inc/release/.github/workflows/checkout.yml@main
  build:
    runs-on: ubuntu-latest
    steps:        
      - name: Setup packages
        run: npm ci
        
      - name: Lint
        run: npm run lint
      
      - name: Unit
        run: npm run test
        
      - name: Build
        run: npm run build
