name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: taskany-inc/release/.github/workflows/checkout.yml@main
        
      - name: Setup packages
        run: npm ci
        
      - name: Lint
        run: npm run lint
      
      - name: Unit
        run: npm run test
