name: Release

on:
  issues:
     types: [opened]

jobs:
  build:
    name: Scheduled Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}
            
      - name: Setup packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit
        run: npm run test
      - name: Shipit
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: | 
          git config --global user.email "sheep@taskany.org"
          git config --global user.name "Taskany Sheep"
          node scripts/release.js
          git checkout -b release/$(cat .release_bot/version)
          git add .
          git commit -n -m "chore: release $(cat .release_bot/version)"
          git push --no-verify origin release/$(cat .release_bot/version)
          gh pr create --title "Release $(cat .release_bot/version)" -F .release_bot/pr_body
